version: 0.2

phases:
  install: # Install AWS CLI, kubectl, and Helm3
    commands:
      - yum update -y  # Added "-y" to automatically confirm
      - echo "yum update done"
      - yum install -y git python3 python3-pip
      - echo "yum install done"
      - pip install awscli
      - curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - helm repo add stable https://charts.helm.sh/stable && helm repo update

  pre_build: # Configure AWS CLI, EKS access, and check readiness
    commands:
      - "helm version"
      - "mkdir -p ~/.kube/"
      - "aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME --role-arn $EKS_CODEBUILD_ROLE_ARN"
      - "chmod 0600 ~/.kube/config"
      - "aws sts get-caller-identity"
